name: CI/CD for Microservices

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
          - name: Pull and Deploy Microservices
            run: |
              # Capitalize MICROSERVICE_NAME
              rem Capitalize MICROSERVICE_NAME using PowerShell
              for /f "delims=" %%i in ('powershell -Command "[string]::ToUpper('${{ vars.MICROSERVICE_NAME }}')"') do set CAPS_MICROSERVICE_NAME=%%i

              echo "Restarting %CAPS_MICROSERVICE_NAME% container..."
