name: CI/CD for Microservices

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
          - name: Pull and Deploy Microservices
            uses: ASzc/change-string-case-action@v1
            with: 
              string: ${{ vars.MICROSERVICE_NAME }}
          - run: |
              echo "${{steps.string.outputs.uppercase}}"
