name: CI/CD for Microservices

on:
  push:
    branches:
      - main

jobs:
    deploy:
      name: Pull and Deploy Microservices
      runs-on: self-hosted
      steps:
        - id: string
          uses: ASzc/change-string-case-action@v6
          with: 
            string: ${{ vars.MICROSERVICE_NAME }}
        - run: |
              echo "${{steps.string.outputs.uppercase}}"
